# Generated by Django 3.1.6 on 2021-02-06 04:58

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('slide_image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='News Picture(*Automatic convert into 500*500 )', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('slide_image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='News Picture(*Automatic convert into 500*500 )', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('slide_image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='News Picture(*Automatic convert into 500*500 )', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('slide_image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='News Picture(*Automatic convert into 500*500 )', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('slide_image5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='News Picture(*Automatic convert into 500*500 )', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('external_video_storage', models.URLField(blank=True, help_text='*Youtube embeded link only')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
