# Generated by Django 3.1.6 on 2021-02-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0002_remove_image_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='model',
        ),
        migrations.AddField(
            model_name='projects',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.image'),
            preserve_default=False,
        ),
    ]
