# Generated by Django 3.1.6 on 2021-02-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0003_auto_20210222_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='model',
            new_name='modelForImage',
        ),
    ]
