# Generated by Django 3.1.6 on 2021-02-06 14:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0003_media_press'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='media',
        ),
        migrations.AddField(
            model_name='press',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন '),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
