# Generated by Django 3.1.6 on 2021-02-23 05:13

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0004_auto_20210222_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_for_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='modelForImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='image_for_projects',
            name='modelForImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.projects'),
        ),
    ]
