# Generated by Django 3.1.6 on 2021-02-23 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0005_auto_20210223_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text=' প্শিরোনাম দিন ', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('external_video_storage', models.URLField(blank=True, help_text='*Youtube embeded link only')),
            ],
        ),
        migrations.CreateModel(
            name='Image_for_covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('modelForImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.covid19')),
            ],
        ),
    ]
