# Generated by Django 3.1.6 on 2021-02-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0007_donate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'ordering': ['created_date']},
        ),
    ]
