# Generated by Django 3.1.6 on 2021-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0008_auto_20210223_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(unique=True)),
                ('name', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
                ('designation', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
                ('occupation', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
                ('organization', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AlterModelOptions(
            name='donate',
            options={'ordering': ['-created_date']},
        ),
    ]
