# Generated by Django 3.1.6 on 2021-02-23 15:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0009_auto_20210223_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Profile Picture', keep_meta=True, quality=0, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='designation',
            field=models.CharField(help_text=' পদবী ', max_length=100),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(help_text=' নাম  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='committee',
            name='occupation',
            field=models.CharField(help_text=' পেশা ', max_length=100),
        ),
        migrations.AlterField(
            model_name='committee',
            name='organization',
            field=models.CharField(help_text=' প্রতিষ্ঠান ', max_length=100),
        ),
    ]
