# Generated by Django 3.1.6 on 2021-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0010_auto_20210223_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='title',
            field=models.CharField(default=1, help_text='কমিটির নাম  ', max_length=100),
            preserve_default=False,
        ),
    ]
