# Generated by Django 3.1.6 on 2021-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0013_advisorcommittee_volunteercommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorcommittee',
            name='Address',
            field=models.CharField(blank=True, help_text=' ঠিকানা ', max_length=100),
        ),
        migrations.AddField(
            model_name='advisorcommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=100),
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='Address',
            field=models.CharField(blank=True, help_text=' ঠিকানা ', max_length=100),
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteercommittee',
            name='Address',
            field=models.CharField(blank=True, help_text=' ঠিকানা ', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteercommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=100),
        ),
        migrations.AlterField(
            model_name='advisorcommittee',
            name='occupation',
            field=models.CharField(blank=True, help_text=' পেশা ', max_length=100),
        ),
        migrations.AlterField(
            model_name='advisorcommittee',
            name='organization',
            field=models.CharField(blank=True, help_text=' প্রতিষ্ঠান ', max_length=100),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='occupation',
            field=models.CharField(blank=True, help_text=' পেশা ', max_length=100),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='organization',
            field=models.CharField(blank=True, help_text=' প্রতিষ্ঠান ', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteercommittee',
            name='designation',
            field=models.CharField(default='স্বেচ্ছাসেবক', help_text=' পদবী ', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteercommittee',
            name='occupation',
            field=models.CharField(blank=True, help_text=' পেশা ', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteercommittee',
            name='organization',
            field=models.CharField(blank=True, help_text=' প্রতিষ্ঠান ', max_length=100),
        ),
    ]
