# Generated by Django 3.1.6 on 2021-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0014_auto_20210223_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteercommittee',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Picture', upload_to='images/'),
        ),
    ]
