# Generated by Django 3.1.6 on 2021-02-24 05:44

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0015_auto_20210223_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='  শিরোনাম দিন ', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='project_title')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='advisorcommittee',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Profile Picture', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Profile Picture', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image_for_covid19',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=-1, size=[500, 500], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image_for_projects',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=-1, size=[500, 500], upload_to='images/'),
        ),
    ]
