# Generated by Django 3.1.6 on 2021-02-24 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0016_auto_20210224_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text=' প্শিরোনাম দিন ', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text=' প্শিরোনাম দিন ', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Image_for_Photo_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=-1, size=[500, 500], upload_to='albums/')),
                ('show_in_homepage', models.BooleanField()),
                ('modelForImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.photo_gallery')),
            ],
        ),
    ]
