# Generated by Django 3.1.6 on 2021-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0017_image_for_photo_gallery_photo_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_gallery',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='photo_gallery',
            name='title',
        ),
        migrations.AddField(
            model_name='image_for_photo_gallery',
            name='subtitle',
            field=models.CharField(blank=True, help_text=' প্শিরোনাম দিন ', max_length=100),
        ),
        migrations.AddField(
            model_name='image_for_photo_gallery',
            name='title',
            field=models.CharField(blank=True, help_text=' প্শিরোনাম দিন ', max_length=100),
        ),
    ]
