# Generated by Django 3.1.6 on 2021-02-24 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0018_auto_20210224_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Link_for_Video_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text=' প্শিরোনাম দিন ', max_length=100)),
                ('external_video_storage', models.URLField(blank=True, help_text='*Youtube embeded link only')),
                ('show_on_homepage', models.BooleanField()),
                ('modelForImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.video_gallery')),
            ],
        ),
    ]
