# Generated by Django 3.1.6 on 2021-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0019_link_for_video_gallery_video_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid19',
            name='external_video_storage',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='external_video_storage',
        ),
        migrations.AlterField(
            model_name='link_for_video_gallery',
            name='external_video_storage',
            field=models.URLField(help_text='*Youtube embeded link only ex.https://www.youtube.com/embed/ebRd6BBlibc'),
        ),
    ]
