# Generated by Django 3.1.6 on 2021-02-24 09:55

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0020_auto_20210224_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' শিরোনাম দিন ', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('reporter_name', models.CharField(help_text=' শিরোনাম দিন ', max_length=100)),
                ('image_top', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='This shows before the content', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/')),
                ('image_bottom', django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='This shows after the content', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
