# Generated by Django 3.1.6 on 2021-02-24 09:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0021_recent_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_news',
            name='image_bottom',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='This shows after the content', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='recent_news',
            name='image_top',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='This shows before the content', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/'),
        ),
    ]
