# Generated by Django 3.1.6 on 2021-02-24 10:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0022_auto_20210224_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_news',
            name='image_bottom',
        ),
        migrations.RemoveField(
            model_name='recent_news',
            name='image_top',
        ),
        migrations.AddField(
            model_name='recent_news',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Optional images', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/'),
        ),
        migrations.AddField(
            model_name='recent_news',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Optional images', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/'),
        ),
        migrations.AddField(
            model_name='recent_news',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Optional images', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='news/'),
        ),
    ]
