# Generated by Django 3.1.6 on 2021-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0023_auto_20210224_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_news',
            name='tag',
            field=models.CharField(default='News', help_text='ট্যাগ লিখুন ', max_length=20),
        ),
        migrations.AlterField(
            model_name='recent_news',
            name='reporter_name',
            field=models.CharField(help_text='রিপর্টারের নাম ', max_length=100),
        ),
    ]
