# Generated by Django 3.1.6 on 2021-02-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0025_volunteerregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerRegistration',
        ),
    ]
