# Generated by Django 3.1.6 on 2021-02-25 11:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0026_delete_volunteerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Size will 300*300', keep_meta=True, quality=-1, size=[300, 300], upload_to='volunteers/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('religion', models.CharField(blank=True, choices=[('I', 'Islam'), ('H', 'Hindu'), ('B', 'Buddha'), ('C', 'Chirstian')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True)),
                ('district', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('about_you', models.TextField(blank=True)),
            ],
        ),
    ]
