# Generated by Django 3.1.6 on 2021-02-26 08:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0027_volunteerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='bannerImage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='এই ছবিটি আপলোড করলে তা হোমপেইজের শেষের অংশের স্লাইডে যুক্ত হবে। সেটি না করতে চাইলে ফাকা রাখুন ', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Size will be 300*300', keep_meta=True, quality=-1, size=[300, 300], upload_to='volunteers/'),
        ),
    ]
