# Generated by Django 3.1.6 on 2021-03-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0029_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+(VE)'), ('A-', 'A-(NE)'), ('B+', 'B+(VE)'), ('B-', 'B-(NE)'), ('O+', 'O+(VE)'), ('O-', 'O-(NE)')], max_length=2)),
                ('date_of_birth', models.DateField(help_text='Must be 18 years')),
                ('address', models.TextField()),
                ('lastDonationDate', models.DateField(blank=True, help_text='Must be 18 years')),
            ],
        ),
    ]
