# Generated by Django 3.1.6 on 2021-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0030_blooddonerregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonerregistration',
            name='lastDonationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
