# Generated by Django 3.1.6 on 2021-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0031_auto_20210301_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
