# Generated by Django 3.1.6 on 2021-03-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0032_auto_20210301_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonerRegistration',
        ),
    ]
