# Generated by Django 3.1.6 on 2021-03-01 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0035_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
