# Generated by Django 3.1.6 on 2021-03-01 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0036_auto_20210301_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorcommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='blooddonerregistration',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='volunteercommittee',
            name='phone',
            field=models.CharField(blank=True, help_text=' ফোন নম্বর ', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
