# Generated by Django 3.1.6 on 2021-04-09 19:30

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0037_auto_20210301_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from='project_title'),
        ),
    ]
