# Generated by Django 3.1.6 on 2021-04-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0039_remove_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='slug',
        ),
    ]
