# Generated by Django 3.1.6 on 2021-04-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0040_remove_donate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='slug',
        ),
    ]
