# Generated by Django 3.1.6 on 2021-04-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0041_remove_about_us_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_news',
            name='slug',
        ),
    ]
