# Generated by Django 3.1.6 on 2021-04-11 10:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0043_auto_20210410_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('AccountNumber', models.CharField(max_length=100)),
                ('DonarAddress', models.TextField()),
                ('Phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='image_for_photo_gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Picture', keep_meta=True, quality=-1, size=[1920, 1080], upload_to='albums/'),
        ),
    ]
