# Generated by Django 3.1.6 on 2021-04-11 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0044_auto_20210411_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationinformation',
            old_name='AccountNumber',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='donationinformation',
            old_name='DonarAddress',
            new_name='donarAddress',
        ),
        migrations.RenameField(
            model_name='donationinformation',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='donationinformation',
            name='Phone',
        ),
        migrations.AddField(
            model_name='donationinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801xxxxxxxxx'.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
