# Generated by Django 3.1.6 on 2021-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0045_auto_20210411_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationinformation',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='donationinformation',
            old_name='donarAddress',
            new_name='donar_address',
        ),
    ]
