# Generated by Django 3.1.6 on 2021-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0046_auto_20210411_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinformation',
            name='donar_address',
            field=models.TextField(blank=True),
        ),
    ]
