# Generated by Django 3.1.6 on 2021-04-11 16:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0047_auto_20210411_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(help_text='MM/DD/YYYY')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' Description ')),
            ],
        ),
    ]
