# Generated by Django 3.1.6 on 2021-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0048_upcomingevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='event_date',
            field=models.DateTimeField(help_text='YYYY/MM/DD HH:MM:SS(International format)'),
        ),
    ]
