# Generated by Django 3.1.6 on 2021-04-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0049_auto_20210411_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingevents',
            options={'ordering': ['-event_date']},
        ),
    ]
