# Generated by Django 3.1.6 on 2021-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0051_fundraise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='raised_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fundraise',
            name='targeted_amount',
            field=models.IntegerField(default=0),
        ),
    ]
