# Generated by Django 3.1.6 on 2021-04-17 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0052_auto_20210414_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraise',
            name='url_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebaybdApp.donate'),
        ),
    ]
