# Generated by Django 3.1.6 on 2021-05-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0053_fundraise_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
