# Generated by Django 3.1.6 on 2021-05-08 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0055_auto_20210508_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='First_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
