# Generated by Django 3.1.6 on 2021-05-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebaybdApp', '0056_auto_20210508_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerregistration',
            name='First_Name',
        ),
    ]
